Fixed Actions & Docker

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,10 +1,8 @@
-ARG JAVA_VERSION=17
-ARG JVM_IMPL=hotspot
+ARG JVM_VERSION=17
 ARG SERVICE_NAME=server
 
-FROM adoptopenjdk:${JAVA_VERSION}-jdk-${JVM_IMPL} AS builder
-
-ARG SERVICE_NAME=server
+FROM eclipse-temurin:${JVM_VERSION}-jdk-focal AS builder
+ARG SERVICE_NAME
 
 RUN set -o errexit -o nounset \
  && apt-get update \
@@ -13,25 +11,52 @@ RUN set -o errexit -o nounset \
 COPY . /src
 WORKDIR /src
 
-RUN chmod +x ./gradlew \
-    && ./gradlew :${SERVICE_NAME}:bootJar --stacktrace --no-daemon
+RUN set -o errexit -o nounset \
+ && chmod +x ./gradlew \
+ && ./gradlew clean :${SERVICE_NAME}:shadowJar :${SERVICE_NAME}:assemble --stacktrace --no-daemon
 
-FROM adoptopenjdk:${JAVA_VERSION}-jre-${JVM_IMPL} AS extractor
-
-ARG SERVICE_NAME=server
+FROM eclipse-temurin:${JVM_VERSION}-jdk-focal AS jre
+ARG JVM_VERSION
+ARG SERVICE_NAME
 
 WORKDIR /src
 
-COPY --from=builder /src/${SERVICE_NAME}/build/libs/${SERVICE_NAME}*.jar cryptic.jar
-RUN java -Djarmode=layertools -jar cryptic.jar extract
+COPY --from=builder /src/${SERVICE_NAME}/build/libs/${SERVICE_NAME}-*-all.jar ${SERVICE_NAME}.jar
 
-FROM adoptopenjdk:${JAVA_VERSION}-jre-${JVM_IMPL}
+RUN set -o errexit -o nounset \
+ && jdeps \
+     --ignore-missing-deps \
+     -q \
+     --multi-release ${JVM_VERSION} \
+     --print-module-deps \
+     ./${SERVICE_NAME}.jar > jre-deps.info \
+ && jlink \
+     --add-modules $(cat jre-deps.info) \
+     --strip-debug \
+     --no-man-pages \
+     --no-header-files \
+     --compress 2 \
+     --output ./jre
+
+FROM eclipse-temurin:${JVM_VERSION}-jdk-focal AS extractor
+ARG SERVICE_NAME
+
+WORKDIR /src
+
+COPY --from=builder /src/${SERVICE_NAME}/build/libs/${SERVICE_NAME}-*.jar ${SERVICE_NAME}.jar
+RUN java -Djarmode=layertools -jar ${SERVICE_NAME}.jar extract
+
+FROM ubuntu:focal
+ARG SERVICE_NAME
+
+ENV JAVA_HOME=/opt/jre
+ENV PATH="/opt/jre/bin:${PATH}"
 
 ENV HTTP_PORT=8080
 ENV MANAGEMENT_PORT=8081
 
-ARG CRYPTIC_USER=cryptic
-ARG CRYPTIC_GROUP=cryptic
+ARG CRYPTIC_USER=cryptic-${SERVICE_NAME}
+ARG CRYPTIC_GROUP=cryptic-${SERVICE_NAME}
 ARG DATA_DIR=/data
 
 RUN set -o errexit -o nounset \
@@ -42,10 +67,20 @@ RUN set -o errexit -o nounset \
  && chown --recursive ${CRYPTIC_USER}:${CRYPTIC_GROUP} /home/${CRYPTIC_USER} \
  \
  && apt-get update \
- && apt-get install -y --no-install-recommends curl jq \
- && rm -rf /var/lib/apt/lists/*
+ && apt-get install -y --no-install-recommends curl jq ca-certificates \
+ && rm -rf /var/lib/apt/lists/* \
+ \
+ && curl -fsSL https://raw.githubusercontent.com/fabric8io-images/run-java-sh/master/fish-pepper/run-java-sh/fp-files/run-java.sh -so /opt/run-java.sh \
+ && chmod +x /opt/run-java.sh
+
+COPY --from=jre /src/jre ${JAVA_HOME}
 
 WORKDIR ${DATA_DIR}
+
+ENV JAVA_APP_DIR=${DATA_DIR}
+ENV JAVA_MAIN_CLASS=org.springframework.boot.loader.JarLauncher
+ENV JAVA_APP_NAME=cryptic-${SERVICE_NAME}
+ENV JAVA_CLASSPATH=/opt/cryptic-${SERVICE_NAME}
 
 USER ${CRYPTIC_USER}:${CRYPTIC_GROUP}
 VOLUME ${DATA_DIR}
@@ -53,13 +88,13 @@ VOLUME ${DATA_DIR}
 EXPOSE ${HTTP_PORT}
 EXPOSE ${MANAGEMENT_PORT}
 
-COPY --from=extractor /src/dependencies/ /opt/cryptic
-COPY --from=extractor /src/spring-boot-loader/ /opt/cryptic
-COPY --from=extractor /src/snapshot-dependencies/ /opt/cryptic
-COPY --from=extractor /src/application/ /opt/cryptic
+COPY --from=extractor /src/dependencies/ /opt/cryptic-${SERVICE_NAME}
+COPY --from=extractor /src/spring-boot-loader/ /opt/cryptic-${SERVICE_NAME}
+COPY --from=extractor /src/snapshot-dependencies/ /opt/cryptic-${SERVICE_NAME}
+COPY --from=extractor /src/application/ /opt/cryptic-${SERVICE_NAME}
 
-ENTRYPOINT ["java", "-cp", "/opt/cryptic", "org.springframework.boot.loader.JarLauncher"]
+ENTRYPOINT ["/opt/run-java.sh"]
 
-HEALTHCHECK --start-period=10s --interval=30s --timeout=3s --retries=3 \
-            CMD curl --silent --fail --request GET "http://localhost:${MANAGEMENT_PORT}/actuator/health" \
-                | jq --exit-status '.status == "UP"' || exit 1
+#HEALTHCHECK --start-period=10s --interval=30s --timeout=3s --retries=3 \
+#            CMD curl --silent --fail --request GET "http://localhost:${MANAGEMENT_PORT}/actuator/health" \
+#                | jq --exit-status '.status == "UP"' || exit 1
